INSERT INTO USUARIOS VALUES (1, 'sebastian moncaleano', 'ASASGSA', 'DASFA');
INSERT INTO USUARIOS VALUES (2, 'Alexa', 'ASASGSA', 'DASFA');
INSERT INTO USUARIOS VALUES (3, 'Evelyn', 'ASASGSA', 'DASFA');
INSERT INTO USUARIOS VALUES (4, 'Fernando', 'ASASGSA', 'DASFA');
INSERT INTO USUARIOS VALUES (5, 'Marax', 'ASASGSA', 'DASFA');
